# Generated by Django 5.2.9 on 2026-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomehead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefield', models.CharField(max_length=20)),
            ],
        ),
    ]
