# Generated by Django 5.2.9 on 2026-01-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_expensehead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expensehead',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incomehead',
            name='namefield',
            field=models.CharField(max_length=50),
        ),
    ]
