# Generated by Django 5.2.9 on 2026-01-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_alter_category_description_alter_expensehead_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensehead',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
