# Generated by Django 5.2.9 on 2026-01-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_expensehead'),
        ('app_user', '0002_expensedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='expensehead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.expensehead'),
        ),
    ]
