# Generated by Django 5.2.9 on 2026-01-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_expensedetails_expensehead'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetails',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensedetails',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
