# Generated by Django 5.2.9 on 2026-01-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_expensedetails_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetails',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
