# Generated by Django 5.2.9 on 2026-01-12 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_alter_expensehead_description'),
        ('app_user', '0005_alter_incomedetails_create_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('amount', models.TextField()),
                ('expensehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.expensehead')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
