# Generated by Django 5.2.9 on 2026-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_budgetdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
