# Generated by Django 5.2.9 on 2026-02-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_alter_expensedetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
