# Generated by Django 5.2.9 on 2026-02-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_alter_expensedetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='incomedetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
