# Generated by Django 5.2.9 on 2026-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_alter_budgetdetails_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdetails',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
